# Site
name: 'Геймер+'
description: 'Приложение к старейшему телеграм-канал про видеоигры на русском языке. Новости, эксклюзивы и немного иронии.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: '/blog'
# disqus: 'demowebsite'
email: 'alex@krushin.me'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    alex:
      name:           Александр Крушин
      site:           https://krushin.me
      avatar:         https://gmr.plus/assets/images/ava_alex.jpg
      bio:            "Издатель"
      email:          alex@krushin.me
      twitter:        https://twitter.com/krushin_ru

    surepin:
      name:           Сергей Сурепин
      site:           https://surepin.me
      avatar:         https://gmr.plus/assets/images/ava_surepin.jpg
      bio:            "Шеф-редактор"
      twitter:        https://twitter.com/iamsuredg

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: team
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]